language: python
dist: focal

python:
  - 3.12

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput
script:
  - black --check .
  - flake8
  - coverage run --source=mysite,polls manage.py test
  - coverage report
  - coverage xml
  - echo "Deploying..."
after_success:
  - git add .coverage coverage.xml
  - echo "COVERALLS_REPO_TOKEN is set to $COVERALLS_REPO_TOKEN"
  - coveralls

env:
  global:
    - COVERALLS_REPO_TOKEN=D4ZNUUP9NmnGkHauBu3jXT6k3LvMBzvt6

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: django-poll
  env: django-env
  bucket_name: elasticbeanstalk-us-east-1-593489176864
  on:
    branch: main