language: python
dist: focal

python:
  - 3.12

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - python manage.py test
  - echo "Deploying..."